### ISSUE TITLE
kernel dead when creating thread with wrong arguments

### ISSUE THREAD

**Issue by xmduhan** [fredokun/cl-jupyter#12]
Run the follow code in a cell，the kernel dead again. I guest this is cause by wrong arguments call.
In [*]:
(defun thread-function (x) x)
(sb-thread:make-thread #'thread-function)

**Comment by fredokun** [comment]
I have to investigate this one, but I think feeding "eval" with thread-related side effects may be somewhat "adventurous".   Here an `SB-INT:SIMPLE-PROGRAM-ERROR` is raised in the child thread (if you use SBCL)... and I think I can only catch errors in the main thread. Most of all, I do not want to replicate the low-level thread library for making it "cl-jupyter-friendly"...  And since the backend is automatically restarted I think this is not so much of a trouble...  So if you use threads, be sure they do not trigger the Lisp debugger except in the main thread.  (anyways, thanks again for raising the issue).

**Comment by xmduhan** [comment]
I probably understand what you mean. Thank you!

**Comment by fredokun** [comment]
I'm closing this one, but note that the condition handling in cl-jupyter is still quite naive.
